2025-03-24 11:43:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Индекс "IDX_USER" уже существует
Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:110)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:106)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:96)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:671)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:620)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:746)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:491)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:365)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:313)
	at java.base/java.lang.Thread.run(Thread.java:1575)
2025-03-24 14:26:17 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Индекс "IDX_USER" уже существует
Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:110)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:106)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:96)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:671)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:620)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:746)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:491)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:365)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:313)
	at java.base/java.lang.Thread.run(Thread.java:1575)
2025-03-24 23:43:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Индекс "IDX_USER" уже существует
Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:110)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:106)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:96)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:671)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:620)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:746)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:491)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:365)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:313)
	at java.base/java.lang.Thread.run(Thread.java:1575)
2025-03-25 00:26:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Индекс "IDX_USER" уже существует
Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:110)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:106)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:96)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:671)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:620)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:746)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:491)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:365)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:313)
	at java.base/java.lang.Thread.run(Thread.java:1575)
2025-03-25 00:43:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Индекс "IDX_USER" уже существует
Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:110)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:106)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:96)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:671)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:620)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:746)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:491)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:365)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:313)
	at java.base/java.lang.Thread.run(Thread.java:1575)
2025-03-25 00:48:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Индекс "IDX_USER" уже существует
Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:110)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:106)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:96)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
	at java.base/java.lang.Thread.run(Thread.java:1575)
2025-03-25 11:29:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Индекс "IDX_USER" уже существует
Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:110)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:106)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:96)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
	at java.base/java.lang.Thread.run(Thread.java:1575)
2025-03-25 11:38:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Индекс "IDX_USER" уже существует
Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:110)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:106)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:96)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
	at java.base/java.lang.Thread.run(Thread.java:1575)
2025-03-25 11:48:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Индекс "IDX_USER" уже существует
Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:110)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:106)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:96)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
	at java.base/java.lang.Thread.run(Thread.java:1575)
2025-03-25 11:54:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Индекс "IDX_USER" уже существует
Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:110)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:106)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:96)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
	at java.base/java.lang.Thread.run(Thread.java:1575)
2025-03-25 12:13:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Индекс "IDX_USER" уже существует
Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:110)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:106)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:96)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
	at java.base/java.lang.Thread.run(Thread.java:1575)
2025-03-25 13:25:10 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Индекс "IDX_USER" уже существует
Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:110)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:106)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:96)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:671)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:620)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:746)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:491)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:365)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:313)
	at java.base/java.lang.Thread.run(Thread.java:1575)
2025-03-25 13:29:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Индекс "IDX_USER" уже существует
Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:110)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:106)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:96)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:671)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:620)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:746)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:491)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:365)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:313)
	at java.base/java.lang.Thread.run(Thread.java:1575)
2025-03-25 13:35:44 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Индекс "IDX_USER" уже существует
Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:110)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:106)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:96)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:671)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:620)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:746)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:491)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:365)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:313)
	at java.base/java.lang.Thread.run(Thread.java:1575)
2025-03-27 22:44:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Индекс "IDX_USER" уже существует
Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:110)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:106)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:96)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:671)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:620)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:746)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:491)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:365)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:313)
	at java.base/java.lang.Thread.run(Thread.java:1575)
2025-03-27 22:57:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Индекс "IDX_USER" уже существует
Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:110)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:106)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:96)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:671)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:620)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:746)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:491)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:365)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:313)
	at java.base/java.lang.Thread.run(Thread.java:1575)
2025-03-28 12:39:17 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Индекс "IDX_USER" уже существует
Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:110)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:106)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:96)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:671)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:620)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:746)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:491)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:365)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:313)
	at java.base/java.lang.Thread.run(Thread.java:1575)
2025-03-28 16:42:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Индекс "IDX_USER" уже существует
Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:110)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:106)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:96)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:671)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:620)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:746)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:491)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:365)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:313)
	at java.base/java.lang.Thread.run(Thread.java:1575)
